### ISSUE TITLE
Issue with environment.yaml file

### ISSUE THREAD

**Issue by supriya-gdptl** [FlyingGiraffe/vnn-neural-implicits#1]
Hello @FlyingGiraffe,

Thank you for sharing the code.
I used `environment.yaml` file given in this repository to create conda environment. However, I am getting following error while importing pytorch:
```
ImportError: /anaconda3/envs/mesh_funcspace/lib/python3.6/site-packages/torch/lib/libmkldnn.so.0: undefined symbol: cblas_sgemm_alloc
```

Could you please share the `requirements.txt` file? It would be helpful to create `virtualenv` and use `pip` to install required packages rather than creating conda environment.

Thank you,
Supriya

**Comment by FlyingGiraffe** [comment]
Hi,

Here's what I get with `pip freeze > requirements.txt`: [requirements.txt](https://github.com/FlyingGiraffe/vnn-neural-implicits/files/7039974/requirements.txt) - but not sure if all the packages are available on PyPI.

My env is borrowed directly from [OccNet](https://github.com/autonomousvision/occupancy_networks) (plus [PyTorch3D](https://pytorch3d.readthedocs.io/en/latest/) to generate 3D transformations) and seems people also
 encountered [the same issue](https://github.com/autonomousvision/occupancy_networks/issues/100) there...

Best,
Congyue

**Comment by supriya-gdptl** [comment]
Thank you for the help.

**Comment by pbsds** [comment]
Took me a while, but I think I've gotten this env to work: 

```yaml
name: vnn-implicit
channels:
  - conda-forge
  - pytorch
  - anaconda
  - pytorch3d
  - defaults
dependencies:
  - cython
  - imageio
  - numpy
  - numpy-base
  - matplotlib
  - matplotlib-base
  - mkl
  - pandas
  - pillow<7
  - pyembree
  - pytest
  - pip
  - python=3.8
  - python-lsp-server
  - pytorch=1.10.2
  - torchvision=0.11.3
  - cudatoolkit=11.3
  - pytorch3d=0.6.2
  - pyyaml<6
  - scikit-learn
  - scikit-image
  - scipy
  - tensorboardx
  - tqdm
  - trimesh
  - pip:
    - h5py
    - plyfile
```
